# Generated by Django 2.1.15 on 2021-06-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erkaklar', models.CharField(max_length=250)),
                ('ayollar', models.CharField(max_length=250)),
                ('hajm', models.CharField(max_length=250)),
                ('hosil', models.CharField(max_length=250)),
                ('fermerlar', models.CharField(max_length=250)),
                ('daromad', models.CharField(max_length=250)),
            ],
        ),
    ]
