# Generated by Django 2.1.15 on 2021-06-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stat',
        ),
    ]
